export const categories = [
    "Fruit Trees", "Ground Covers", "Indoor Plants", "Native Plants", "New Arrivals", "Palms", "Seasonal", "Shrubs", "Succulents", "Trees",
  ];

  export const products = [
    { id: 6, name: "California Fuchsia", category: "Ground Covers", image: "/ground-covers1.jpg" },
    { id: 28, name: "Arctic snow", category: "Shrubs", image: "/shrubs1.jpg" },
    { id: 1, name: "Mountain thatch palm", category: "Palms", image: "/palms1.jpg" },
    { id: 2, name: "Grape,Enab", category: "Fruit Trees", image: "/fruit-trees1.jpg" },
    { id: 3, name: "White mulberry,Toot", category: "Fruit Trees", image: "/fruit-trees2.jpg" },
    { id: 4, name: "Mandarin", category: "Fruit Trees", image: "/fruit-trees3.jpg" },
    { id: 5, name: "Pineapple", category: "Fruit Trees", image: "/fruit-trees4.jpg" },
    { id: 7, name: "Bush clockvine", category: "Ground Covers", image: "/ground-covers2.jpg" },
    { id: 8, name: "Elephant plant", category: "Ground Covers", image: "/ground-covers3.jpg" },
    { id: 9, name: "Portulaca,Beladear", category: "Ground Covers", image: "/ground-covers4.jpg" },
    { id: 10, name: "Purple heart", category: "Indoor Plants", image: "/indoor-plants1.jpg" },
    { id: 11, name: "Cape primrose", category: "Indoor Plants", image: "/indoor-plants2.jpg" },
    { id: 12, name: "Dinner plate Aralia", category: "Indoor Plants", image: "/indoor-plants3.jpg" },
    { id: 13, name: "Cabbage tree", category: "Indoor Plants", image: "/indoor-plants4.jpg" },
    { id: 14, name: "Red Cassia", category: "Native Plants", image: "/native-plants1.jpg" },
    { id: 15, name: "Shoestring Acacia", category: "Native Plants", image: "/native-plants2.jpg" },
    { id: 16, name: "Tamarix,Athel", category: "Native Plants", image: "/native-plants3.jpg" },
    { id: 17, name: "Jojoba", category: "Native Plants", image: "/native-plants4.jpg" },
    { id: 18, name: "Olea europaea", category: "New Arrivals", image: "/new-arrivals1.jpg" },
    { id: 19, name: "Azadirachta indica", category: "New Arrivals", image: "/new-arrivals2.jpg" },
    { id: 20, name: "Millingtonia hortensis", category: "New Arrivals", image: "/new-arrivals3.jpg" },
    { id: 21, name: "Bamboo palm", category: "Palms", image: "/palms2.jpg" },
    { id: 22, name: "Macarthur palm", category: "Palms", image: "/palms3.jpg" },
    { id: 23, name: "Pacific fan palm", category: "Palms", image: "/palms4.jpg" },
    { id: 24, name: "Star cluster", category: "Seasonal", image: "/sessional1.jpg" },
    { id: 25, name: "Jimson weed", category: "Seasonal", image: "/sessional2.jpg" },
    { id: 26, name: "Snapdragon,Thum as samaka", category: "Seasonal", image: "/sessional3.jpg" },
    { id: 27, name: "Joseph’s coat", category: "Seasonal", image: "/sessional4.jpg" },
    { id: 29, name: "Star Jasmine", category: "Shrubs", image: "/shrub2.jpg" },
    { id: 30, name: "Orange bells", category: "Shrubs", image: "/shrub3.jpg" },
    { id: 31, name: "Cape honeysuckle", category: "Shrubs", image: "/shrub4.jpg" },
    { id: 32, name: "Cape speckled Aloe", category: "Succulents", image: "/succulents1.jpg" },
    { id: 33, name: "Century plant", category: "Succulents", image: "/succulents2.jpg" },
    { id: 34, name: "Beaked Yucca", category: "Succulents", image: "/succulents3.jpg" },
    { id: 35, name: "Adam’s needle", category: "Succulents", image: "/succulents4.jpg" },
    { id: 36, name: "Chinese elm", category: "Trees", image: "/trees1.jpg" },
    { id: 37, name: "Tipu tree", category: "Trees", image: "/trees2.jpg" },
    { id: 38, name: "Aden apple", category: "Trees", image: "/trees3.jpg" },
    { id: 39, name: "Pink trumpet tree", category: "Trees", image: "/trees4.jpg" },
    { id: 40, name: "Pink trumpet tree", category: "Trees", image: "/trees5.jpg" },
    { id: 41, name: "African tulip tree", category: "Trees", image: "/trees6.jpg" },
    { id: 42, name: "Red Plumeria", category: "Trees", image: "/trees7.jpg" },
    { id: 43, name: "Arborvitae", category: "Trees", image: "/trees8.jpg" },
    { id: 44, name: "Yellow flame tree", category: "Trees", image: "/trees9.jpg" },
    { id: 45, name: "China berry", category: "Trees", image: "/trees10.jpg" },
    { id: 46, name: "Dombeya", category: "Trees", image: "/trees11.jpg" },
    { id: 47, name: "Bo-tree,Fikas lissan al asfour", category: "Trees", image: "/trees12.jpg" },
    { id: 48, name: "Rusty fig", category: "Trees", image: "/trees13.jpg" },
    { id: 49, name: "Indian rosewood,Sarsoa", category: "Trees", image: "/trees14.jpg" },
    { id: 50, name: "Red ironbark", category: "Trees", image: "/trees15.jpg" },
    { id: 51, name: "Silk cotton tree", category: "Trees", image: "/trees16.jpg" },
    { id: 52, name: "Siamese Senna", category: "Shrubs", image: "/shrub5.jpg" },
    { id: 53, name: "Sultani rose", category: "Shrubs", image: "/shrub6.jpg" },
    { id: 54, name: "Scarlet firethorn", category: "Shrubs", image: "/shrub7.jpg" },
    { id: 55, name: "Purple false Eranthemum", category: "Shrubs", image: "/shrub8.jpg" },
    { id: 56, name: "Plumbago", category: "Shrubs", image: "/shrub9.jpg" },
    { id: 57, name: "Mock orange", category: "Shrubs", image: "/shrub10.jpg" },
    { id: 58, name: "Gardenia", category: "Shrubs", image: "/shrub11.jpg" },
    { id: 59, name: "Japanese Euonymus", category: "Shrubs", image: "/shrub12.jpg" },
    { id: 60, name: "False heather", category: "Shrubs", image: "/shrub13.jpg" },
    { id: 61, name: "Queen of the day", category: "Shrubs", image: "/shrub14.jpg" },
    { id: 62, name: "Golden berry", category: "Shrubs", image: "/shrub15.jpg" },
    { id: 63, name: "Grand Crinum", category: "Shrubs", image: "/shrub16.jpg" },
    { id: 64, name: "Evolvulus", category: "Ground Covers", image: "/ground-covers5.jpg" },
    { id: 65, name: "Trailing Lantana", category: "Ground Covers", image: "/ground-covers6.jpg" },
    { id: 66, name: "Lantana", category: "Ground Covers", image: "/ground-covers7.jpg" },
    { id: 67, name: "Clitoria", category: "Ground Covers", image: "/ground-covers8.jpg" },
    { id: 68, name: "Asparagus fern", category: "Ground Covers", image: "/ground-covers9.jpg" },
    { id: 69, name: "Coral vine,Murjan", category: "Ground Covers", image: "/ground-covers10.jpg" },
    { id: 70, name: "Goat’s foot creeper", category: "Ground Covers", image: "/ground-covers11.jpg" },
    { id: 71, name: "Mother-in-lawç¿s tongue", category: "Ground Covers", image: "/ground-covers12.jpg" },
    { id: 72, name: "Lippia,Berbin al Jedi", category: "Ground Covers", image: "/ground-covers13.jpg" },
    { id: 73, name: "Ice plant", category: "Ground Covers", image: "/ground-covers14.jpg" },
    { id: 75, name: "Sweet potato", category: "Ground Covers", image: "/ground-covers16.jpg" },
    { id: 76, name: "Toothbrush tree,Meswak", category: "Native Plants", image: "/native-plants5.jpg" },
    { id: 77, name: "Ghaf tree,Ghaf", category: "Native Plants", image: "/native-plants6.jpg" },
    { id: 78, name: "Manila tamarind,Lawz hindi", category: "Native Plants", image: "/native-plants7.jpg" },
    { id: 79, name: "Mexican Palo Verde", category: "Native Plants", image: "/native-plants8.jpg" },
    { id: 80, name: "Desert thorn,Ghasad", category: "Native Plants", image: "/native-plants9.jpg" },
    { id: 81, name: "Speed tree", category: "Native Plants", image: "/native-plants10.jpg" },
    { id: 82, name: "Little leaf palo verde", category: "Native Plants", image: "/native-plants11.jpg" },
    { id: 83, name: "Sodom’s apple,Ashar", category: "Native Plants", image: "/native-plants12.jpg" },
    { id: 84, name: "Frankincense,Al luba’n", category: "Native Plants", image: "/native-plants13.jpg" },
    { id: 85, name: "Giant reed,Ghab", category: "Native Plants", image: "/native-plants14.jpg" },
    { id: 86, name: "Umbrella thorn,Samur", category: "Native Plants", image: "/native-plants15.jpg" },
    { id: 87, name: "Arabian gum tree,Babul", category: "Native Plants", image: "/native-plants16.jpg" },
    { id: 88, name: "Ribbon bush", category: "Seasonal", image: "/sessional5.jpg" },
    { id: 89, name: "Woolly yarrow", category: "Seasonal", image: "/sessional6.jpg" },
    { id: 90, name: "Chinese lanterns", category: "Seasonal", image: "/sessional7.jpg" },
    { id: 91, name: "Cineraria", category: "Seasonal", image: "/sessional8.jpg" },
    { id: 92, name: "Trailing Gazania", category: "Seasonal", image: "/sessional9.jpg" },
    { id: 93, name: "Zinnia", category: "Seasonal", image: "/sessional10.jpg" },
    { id: 94, name: "Verbena peruviana", category: "Seasonal", image: "/sessional11.jpg" },
    { id: 95, name: "CATHARANTHUS ROSEUS", category: "Seasonal", image: "/sessional12.jpg" },
    { id: 96, name: "SALVIA SPLENDENS", category: "Seasonal", image: "/sessional13.jpg" },
    { id: 97, name: "Salvia", category: "Seasonal", image: "/sessional14.jpg" },
    { id: 98, name: "Salvia mix", category: "Seasonal", image: "/sessional15.jpg" },
    { id: 99, name: "pansy yellow blotch", category: "Seasonal", image: "/sessional16.jpg" },
    { id: 100, name: "Date Palm", category: "Palms", image: "/palms5.jpg" },
    { id: 101, name: "Washingtonia Robusta", category: "Palms", image: "/palms6.jpg" },
    { id: 102, name: "Bismarkia Palm", category: "Palms", image: "/palms7.jpg" },
    { id: 103, name: "Copernicia Alba", category: "Palms", image: "/palms8.jpg" },
    { id: 104, name: "Royal Palm", category: "Palms", image: "/palms9.jpg" },
    { id: 105, name: "Phoenix Robelinii", category: "Palms", image: "/palms10.jpg" },
    { id: 106, name: "Livistona Rotundifolia", category: "Palms", image: "/palms11.jpg" },
    { id: 107, name: "Howea forsteriana (kentia palm)", category: "Palms", image: "/palms12.jpg" },
    { id: 108, name: "Chamaerops humilis", category: "Palms", image: "/palms13.jpg" },
    { id: 109, name: "Coconut palm", category: "Palms", image: "/palms14.jpg" },
    { id: 110, name: "Cycas Revoluta", category: "Palms", image: "/palms15.jpg" },
    { id: 111, name: "Wodyetia bifurcata ( Foxtail Palm )", category: "Palms", image: "/palms16.jpg" },

// trees
    { id: 112, name: "Tamarindus indica", category: "Trees", image: "/trees17.jpg" },
    { id: 113, name: " Terminalia catappa", category: "Trees", image: "/trees18.jpg" },
    { id: 114, name: " Tabebuia argentea", category: "Trees", image: "/trees19.jpg" },
    { id: 115, name: " Pongamia glabra", category: "Trees", image: "/trees20.jpg" },
    { id: 116, name: "Prosopis cineraria", category: "Trees", image: "/trees21.jpg" },
    { id: 117, name: "Ficus religiosa", category: "Trees", image: "/trees22.jpg" },
    { id: 118, name: "Delonix regia", category: "Trees", image: "/trees23.jpg" },
    { id: 119, name: " Cordia sebestena", category: "Trees", image: "/trees24.jpg" },
    { id: 120, name: " Azadirachta indica", category: "Trees", image: "/trees25.jpg" },
    { id: 121, name: " Albizia lebbeck", category: "Trees", image: "/trees26.jpg" },
    { id: 122, name: " Albizia julibrissin", category: "Trees", image: "/trees27.jpg" },
    { id: 123, name: " Acacia arabica", category: "Trees", image: "/trees28.jpg" },
    { id: 124, name: " Millingtonia hortensis", category: "Trees", image: "/trees29.jpg" },
    { id: 125, name: " Acacia farnesiana", category: "Trees", image: "/trees30.jpg" },
    { id: 126, name: "Plumeria Obtusa", category: "Trees", image: "/trees31.jpg" },
    { id: 127, name: "Spathodea campanulata", category: "Trees", image: "/trees32.jpg" },

    

//  Shrub
{ id: 128, name: "Caesalpinia pulcherrima", category: "Shrubs", image: "/shrub17.jpg" },
{ id: 129, name: "Leucophyllum frutescens", category: "Shrubs", image: "/shrub18.jpg" },
{ id: 130, name: "Dodonaea viscosa", category: "Shrubs", image: "/shrub19.jpg" },
{ id: 131, name: "Bougainvillea Singapore pink", category: "Shrubs", image: "/shrub20.jpg" },
{ id: 132, name: "Bougainvillea Singapore pink", category: "Shrubs", image: "/shrub21.jpg" },
{ id: 133, name: "Wrightia religiosa", category: "Shrubs", image: "/shrub22.jpg" },
{ id: 134, name: "Thevetia Peruviana", category: "Shrubs", image: "/shrub23.jpg" },
{ id: 135, name: "Tecomaria capensis", category: "Shrubs", image: "/shrub24.jpg" },
{ id: 136, name: "TECOMA STANS", category: "Shrubs", image: "/shrub25.jpg" },
{ id: 137, name: "Murraya paniculata", category: "Shrubs", image: "/shrub26.jpg" },
{ id: 138, name: "Jatropha pandurifolia", category: "Shrubs", image: "/shrub27.jpg" },
{ id: 139, name: "Ixora coccinea “Yellow”", category: "Shrubs", image: "/shrub28.jpg" },
{ id: 140, name: "Ixora coccinea Red", category: "Shrubs", image: "/shrub29.jpg" },
{ id: 141, name: "Ixora chinensis yellow", category: "Shrubs", image: "/shrub30.jpg" },
{ id: 142, name: "Cassia surattensis", category: "Shrubs", image: "/shrub31.jpg" },
{ id: 143, name: "Carissa grandiflora", category: "Shrubs", image: "/shrub32.jpg" },
{ id: 144, name: "Cassia Alata", category: "Shrubs", image: "/shrub33.jpg" },
{ id: 145, name: "HIBISCUS ROSA SINENSIS", category: "Shrubs", image: "/shrub34.png" },
{ id: 146, name: "Vitex rotundifolia", category: "Shrubs", image: "/shrub35.jpg" },
{ id: 147, name: "Tecoma smithii", category: "Shrubs", image: "/shrub36.jpg" },

// Ground Covers
{ id: 148, name: "Lantana", category: "Ground Covers", image: "/ground-covers17.jpg" },
{ id: 149, name: "Clitoria", category: "Ground Covers", image: "/ground-covers18.jpg" },
{ id: 150, name: "Goat’s foot creeper", category: "Ground Covers", image: "/ground-covers19.jpg" },
{ id: 151, name: "Lampranthus spectabilis", category: "Ground Covers", image: "/ground-covers20.jpg" },
{ id: 74, name: "Coastal Morning Glory", category: "Ground Covers", image: "/ground-covers15.jpg" },
{ id: 152, name: "Portulaca grandiflora", category: "Ground Covers", image: "/ground-covers20.jpg" },
{ id: 153, name: "Tradescantia spathacea ( Rhoeo discolor )", category: "Ground Covers", image: "/ground-covers21.jpg" },
{ id: 154, name: "Portulacaria afra", category: "Ground Covers", image: "/ground-covers22.jpg" },
{ id: 155, name: "Asystasia gangetica", category: "Ground Covers", image: "/ground-covers23.jpg" },
{ id: 156, name: "Wedelia trilobata", category: "Ground Covers", image: "/ground-covers24.jpg" },
{ id: 157, name: "Alternanthera amoena", category: "Ground Covers", image: "/ground-covers25.jpg" },
{ id: 158, name: "Mandevilla", category: "Ground Covers", image: "/ground-covers26.png" },
{ id: 159, name: "ANTIGONON LEPTOPUS", category: "Ground Covers", image: "/ground-covers27.jpg" },
{ id: 160, name: "Atriplex semibaccata", category: "Ground Covers", image: "/ground-covers28.jpg" },

// Sessional
{ id: 161, name: "Petunia white", category: "Seasonal", image: "/sessional17.jpg" },
{ id: 162, name: "Petunia “Mix”", category: "Seasonal", image: "/sessional18.jpg" },
{ id: 163, name: "Marigold Mix", category: "Seasonal", image: "/sessional19.jpg" },
{ id: 164, name: "Ageratum", category: "Seasonal", image: "/sessional20.jpg" },
{ id: 165, name: "Celosia cristata", category: "Seasonal", image: "/sessional21.jpg" },

// Native Plants
{ id: 165, name: "Sweet Acacia,Anbar", category: "Native Plants", image: "/native-plants17.jpg" },
{ id: 166, name: " Acacia arabica", category: "Native Plants", image: "/trees28.jpg" },
{ id: 167, name: " Acacia farnesiana", category: "Native Plants", image: "/trees30.jpg" },
{ id: 168, name: " Parkinsonia aculeata", category: "Native Plants", image: "/native-plants18.jpg" },
{ id: 169, name: " Acacia tortilis", category: "Native Plants", image: "/native-plants19.jpg" },
{ id: 170, name: " Cassia roxburghii", category: "Native Plants", image: "/native-plants20.jpg" },
{ id: 171, name: " Acacia stenophylla", category: "Native Plants", image: "/native-plants21.jpg" },

// Succulents 
{ id: 172, name: "Aloe microstigma", category: "Succulents", image: "/succulents5.jpg" },
{ id: 173, name: "Agave attenuata Variegata", category: "Succulents", image: "/succulents6.jpg" },
{ id: 174, name: "Agave angustifolia", category: "Succulents", image: "/succulents7.jpg" },
{ id: 175, name: "Agave americana marginata", category: "Succulents", image: "/succulents8.jpg" },
{ id: 176, name: "Euphorbia mix", category: "Succulents", image: "/succulents9.jpg" },
{ id: 177, name: "Euphorbia milii", category: "Succulents", image: "/succulents10.jpg" },
{ id: 178, name: "Sansevieria trifasciata", category: "Succulents", image: "/succulents11.jpg" },
{ id: 179, name: "Euphorbia tirucalli", category: "Succulents", image: "/succulents12.jpg" },
{ id: 180, name: "Adenium obesum", category: "Succulents", image: "/succulents13.jpg" },
{ id: 181, name: "Echino cactus", category: "Succulents", image: "/succulents14.jpg" },

  ];