export const categories = [
    "Fruit Trees", "Ground Covers", "Indoor Plants", "Native Plants", "New Arrivals", "Palms", "Seasonal", "Shrubs", "Succulents", "Trees",
  ];

  export const products = [
    { id: 6, name: "California Fuchsia", category: "Ground Covers", image: "/ground-covers1.jpg" },
    { id: 28, name: "Arctic snow", category: "Shrubs", image: "/shrubs1.jpg" },
    { id: 1, name: "Mountain thatch palm", category: "Palms", image: "/palms1.jpg" },
    { id: 2, name: "Grape,Enab", category: "Fruit Trees", image: "/fruit-trees1.jpg" },
    { id: 3, name: "White mulberry,Toot", category: "Fruit Trees", image: "/fruit-trees2.jpg" },
    { id: 4, name: "Mandarin", category: "Fruit Trees", image: "/fruit-trees3.jpg" },
    { id: 5, name: "Pineapple", category: "Fruit Trees", image: "/fruit-trees4.jpg" },
    { id: 7, name: "Bush clockvine", category: "Ground Covers", image: "/ground-covers2.jpg" },
    { id: 8, name: "Elephant plant", category: "Ground Covers", image: "/ground-covers3.jpg" },
    { id: 9, name: "Portulaca,Beladear", category: "Ground Covers", image: "/ground-covers4.jpg" },
    { id: 10, name: "Purple heart", category: "Indoor Plants", image: "/indoor-plants1.jpg" },
    { id: 11, name: "Cape primrose", category: "Indoor Plants", image: "/indoor-plants2.jpg" },
    { id: 12, name: "Dinner plate Aralia", category: "Indoor Plants", image: "/indoor-plants3.jpg" },
    { id: 13, name: "Cabbage tree", category: "Indoor Plants", image: "/indoor-plants4.jpg" },
    { id: 14, name: "Red Cassia", category: "Native Plants", image: "/native-plants1.jpg" },
    { id: 15, name: "Shoestring Acacia", category: "Native Plants", image: "/native-plants2.jpg" },
    { id: 16, name: "Tamarix,Athel", category: "Native Plants", image: "/native-plants3.jpg" },
    { id: 17, name: "Jojoba", category: "Native Plants", image: "/native-plants4.jpg" },
    { id: 18, name: "Olea europaea", category: "New Arrivals", image: "/new-arrivals1.jpg" },
    { id: 19, name: "Azadirachta indica", category: "New Arrivals", image: "/new-arrivals2.jpg" },
    { id: 20, name: "Millingtonia hortensis", category: "New Arrivals", image: "/new-arrivals3.jpg" },
    { id: 21, name: "Bamboo palm", category: "Palms", image: "/palms2.jpg" },
    { id: 22, name: "Macarthur palm", category: "Palms", image: "/palms3.jpg" },
    { id: 23, name: "Pacific fan palm", category: "Palms", image: "/palms4.jpg" },
    { id: 24, name: "Star cluster", category: "Seasonal", image: "/sessional1.jpg" },
    { id: 25, name: "Jimson weed", category: "Seasonal", image: "/sessional2.jpg" },
    { id: 26, name: "Snapdragon,Thum as samaka", category: "Seasonal", image: "/sessional3.jpg" },
    { id: 27, name: "Joseph’s coat", category: "Seasonal", image: "/sessional4.jpg" },
    { id: 29, name: "Star Jasmine", category: "Shrubs", image: "/shrub2.jpg" },
    { id: 30, name: "Orange bells", category: "Shrubs", image: "/shrub3.jpg" },
    { id: 31, name: "Cape honeysuckle", category: "Shrubs", image: "/shrub4.jpg" },
    { id: 32, name: "Cape speckled Aloe", category: "Succulents", image: "/succulents1.jpg" },
    { id: 33, name: "Century plant", category: "Succulents", image: "/succulents2.jpg" },
    { id: 34, name: "Beaked Yucca", category: "Succulents", image: "/succulents3.jpg" },
    { id: 35, name: "Adam’s needle", category: "Succulents", image: "/succulents4.jpg" },
    { id: 36, name: "Chinese elm", category: "Trees", image: "/trees1.jpg" },
    { id: 37, name: "Tipu tree", category: "Trees", image: "/trees2.jpg" },
    { id: 38, name: "Aden apple", category: "Trees", image: "/trees3.jpg" },
    { id: 39, name: "Pink trumpet tree", category: "Trees", image: "/trees4.jpg" },
    { id: 40, name: "Pink trumpet tree", category: "Trees", image: "/trees5.jpg" },
    { id: 41, name: "African tulip tree", category: "Trees", image: "/trees6.jpg" },
    { id: 42, name: "Red Plumeria", category: "Trees", image: "/trees7.jpg" },
    { id: 43, name: "Arborvitae", category: "Trees", image: "/trees8.jpg" },
    { id: 44, name: "Yellow flame tree", category: "Trees", image: "/trees9.jpg" },
    { id: 45, name: "China berry", category: "Trees", image: "/trees10.jpg" },
    { id: 46, name: "Dombeya", category: "Trees", image: "/trees11.jpg" },
    { id: 47, name: "Bo-tree,Fikas lissan al asfour", category: "Trees", image: "/trees12.jpg" },
    { id: 48, name: "Rusty fig", category: "Trees", image: "/trees13.jpg" },
    { id: 49, name: "Indian rosewood,Sarsoa", category: "Trees", image: "/trees14.jpg" },
    { id: 50, name: "Red ironbark", category: "Trees", image: "/trees15.jpg" },
    { id: 51, name: "Silk cotton tree", category: "Trees", image: "/trees16.jpg" },
    { id: 52, name: "Siamese Senna", category: "Shrubs", image: "/shrub5.jpg" },
    { id: 53, name: "Sultani rose", category: "Shrubs", image: "/shrub6.jpg" },
    { id: 54, name: "Scarlet firethorn", category: "Shrubs", image: "/shrub7.jpg" },
    { id: 55, name: "Purple false Eranthemum", category: "Shrubs", image: "/shrub8.jpg" },
    { id: 56, name: "Plumbago", category: "Shrubs", image: "/shrub9.jpg" },
    { id: 57, name: "Mock orange", category: "Shrubs", image: "/shrub10.jpg" },
    { id: 58, name: "Gardenia", category: "Shrubs", image: "/shrub11.jpg" },
    { id: 59, name: "Japanese Euonymus", category: "Shrubs", image: "/shrub12.jpg" },
    { id: 60, name: "False heather", category: "Shrubs", image: "/shrub13.jpg" },
    { id: 61, name: "Queen of the day", category: "Shrubs", image: "/shrub14.jpg" },
    { id: 62, name: "Golden berry", category: "Shrubs", image: "/shrub15.jpg" },
    { id: 63, name: "Grand Crinum", category: "Shrubs", image: "/shrub16.jpg" },
    { id: 64, name: "Evolvulus", category: "Ground Covers", image: "/ground-covers5.jpg" },
    { id: 65, name: "Trailing Lantana", category: "Ground Covers", image: "/ground-covers6.jpg" },
    { id: 66, name: "Lantana", category: "Ground Covers", image: "/ground-covers7.jpg" },
    { id: 67, name: "Clitoria", category: "Ground Covers", image: "/ground-covers8.jpg" },
    { id: 68, name: "Asparagus fern", category: "Ground Covers", image: "/ground-covers9.jpg" },
    { id: 69, name: "Coral vine,Murjan", category: "Ground Covers", image: "/ground-covers10.jpg" },
    { id: 70, name: "Goat’s foot creeper", category: "Ground Covers", image: "/ground-covers11.jpg" },
    { id: 71, name: "Mother-in-lawç¿s tongue", category: "Ground Covers", image: "/ground-covers12.jpg" },
    { id: 72, name: "Lippia,Berbin al Jedi", category: "Ground Covers", image: "/ground-covers13.jpg" },
    { id: 73, name: "Ice plant", category: "Ground Covers", image: "/ground-covers14.jpg" },
    { id: 74, name: "Coastal Morning Glory", category: "Ground Covers", image: "/ground-covers15.jpg" },
    { id: 75, name: "Sweet potato", category: "Ground Covers", image: "/ground-covers16.jpg" },
    { id: 76, name: "Toothbrush tree,Meswak", category: "Native Plants", image: "/native-plants5.jpg" },
    { id: 77, name: "Ghaf tree,Ghaf", category: "Native Plants", image: "/native-plants6.jpg" },
    { id: 78, name: "Manila tamarind,Lawz hindi", category: "Native Plants", image: "/native-plants7.jpg" },
    { id: 79, name: "Mexican Palo Verde", category: "Native Plants", image: "/native-plants8.jpg" },
    { id: 80, name: "Desert thorn,Ghasad", category: "Native Plants", image: "/native-plants9.jpg" },
    { id: 81, name: "Speed tree", category: "Native Plants", image: "/native-plants10.jpg" },
    { id: 82, name: "Little leaf palo verde", category: "Native Plants", image: "/native-plants11.jpg" },
    { id: 83, name: "Sodom’s apple,Ashar", category: "Native Plants", image: "/native-plants12.jpg" },
    { id: 84, name: "Frankincense,Al luba’n", category: "Native Plants", image: "/native-plants13.jpg" },
    { id: 85, name: "Giant reed,Ghab", category: "Native Plants", image: "/native-plants14.jpg" },
    { id: 86, name: "Umbrella thorn,Samur", category: "Native Plants", image: "/native-plants15.jpg" },
    { id: 87, name: "Arabian gum tree,Babul", category: "Native Plants", image: "/native-plants16.jpg" },
    { id: 88, name: "Ribbon bush", category: "Seasonal", image: "/sessional5.jpg" },
    { id: 89, name: "Woolly yarrow", category: "Seasonal", image: "/sessional6.jpg" },
    { id: 90, name: "Chinese lanterns", category: "Seasonal", image: "/sessional7.jpg" },
    { id: 91, name: "Cineraria", category: "Seasonal", image: "/sessional8.jpg" },
    { id: 92, name: "Trailing Gazania", category: "Seasonal", image: "/sessional9.jpg" },
    { id: 93, name: "Zinnia", category: "Seasonal", image: "/sessional10.jpg" },
    { id: 94, name: "Verbena peruviana", category: "Seasonal", image: "/sessional11.jpg" },
    { id: 95, name: "CATHARANTHUS ROSEUS", category: "Seasonal", image: "/sessional12.jpg" },
    { id: 96, name: "SALVIA SPLENDENS", category: "Seasonal", image: "/sessional13.jpg" },
    { id: 97, name: "Salvia", category: "Seasonal", image: "/sessional14.jpg" },
    { id: 98, name: "Salvia mix", category: "Seasonal", image: "/sessional15.jpg" },
    { id: 99, name: "pansy yellow blotch", category: "Seasonal", image: "/sessional16.jpg" },
  ];