export const plantData = {
  6: {
    name: "California Fuchsia",
    family: "Epilobium",
    uses: "An evergreen, flowering, low spreading, rangy, perennial groundcover, sub-shrub or shrub. Much branched with stems upright and somewhat arching having a generally open branching pattern.",
    size: "30 – 60 Centi Metre",
    location:"Full sun to partial shade",
    soil: "Accepts most soils.",
    Fertiliser:"14.14.14 NPK – Spring and summer",
    water:"",
    plantNo: "864",
    category: "Ground Covers",
    image: "/california-fuchsia.jpg",
    relatedPlants: [
      { name: "Carissa Green Carpet", image: "/id-6-related-1.jpg", link: "#" },
      {
        name: "Atriplex glauca",
        image: "/id-6-related-2.jpg",
        link: "#",
      },
      { name: "Wedelia trilobata", image: "/id-6-related-3.jpg", link: "#" },
      { name: "Setcreasea purpurea", image: "/id-6-related-4.jpg", link: "#" },
    ],
  },
  28: {
    name: "Arctic snow",
    family: "Wrightia",
    uses: "An evergreen, cold deciduous, flowering, perennial shrub with erect, twiggy branches and many short, lateral branchlets.",
    size: "1 – 2 Metre",
    location:"Full sun to partial shade",
    soil: "Organically enriched dune sand.",
    Fertiliser:"13.13.13 NPK – Spring",
    water:"",
    plantNo: "860",
    category: "Shrubs",
    image: "/shrubs1.jpg",
    relatedPlants: [
      { name: "Leptadenia pyrotechnica", image: "/id-28-related-1.jpg", link: "#" },
      {
        name: "Tecoma smithii",
        image: "/id-28-related-2.jpg",
        link: "#",
      },
      { name: "Tecoma stans", image: "/id-28-related-3.jpg", link: "#" },
      { name: "Leucophyllum “Green Cloud", image: "/id-28-related-4.jpg", link: "#" },
    ],
  },
};